[project]
authors = [{ name = "susopeiz", email = "susopeiz@gmail.com" }, { name = "saschahofmann", email = "sascha.kelevra@gmail.com" }]
dependencies = []
name = "xids"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
indicator_delta_scaling = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
xarray = ">=2026.4.0,<2027"
zarr = ">=3.1.6,<4"
dask = ">=2026.3.0,<2027"

[tool.pixi.feature.dev.dependencies]
xsdba = "*"
jupyter = ">=1.1.1,<2"
xclim = ">=0.60.0,<0.61"
nc-time-axis = ">=1.4.1,<2"
ruff = ">=0.15.11,<0.16"

[tool.pixi.environments]
default = ["dev"]


[dependency-groups]
dev = ["ibicus>=1.2.0,<2"]
